### ISSUE TITLE
error TS2307: Cannot find module '@spruceid/kepler-sdk-wrapper' or its corresponding type declarations.

### ISSUE THREAD

**Issue by swkpku** [spruceid/kepler-sdk#50]
can't run example/ on mac OS, got error:
`error TS2307: Cannot find module '@spruceid/kepler-sdk-wrapper' or its corresponding type declarations.`

The reason of this error is because module '@spruceid/kepler-sdk-wrapper' is not correctly built. Building module '@spruceid/kepler-sdk-wrapper' requires a `sed` command in wrapper/build.sh, and `sed` command in mac OS X requires the extension to be explicitly specified. To mitigate this issue, I had to add a empty string after `sed -i` like this `sed -i '' 's/\(..\/..\/wasm\)/.\/wasm/g'`, then everything works.

I'm not sure if this fix works with other operating system, but I guess you might be interested to test and fix it.

**Comment by cobward** [comment]
Hey sorry about this, I forgot that the default installation of `sed` is openbsd for mac. I'll replace this with something that will work on all unix-based platforms.
